packages:
  - 'packages/ai'
  - 'packages/aci'
  - 'packages/browser'
  - 'packages/dxt'
  - 'packages/jetbrains'
  - 'packages/mcp'
  - 'packages/tools'
  - 'packages/vscode'
  - 'apps/*'

onlyBuiltDependencies:
  - better-sqlite3
